# Generated by Django 5.0.6 on 2026-07-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prediction",
            name="language_used",
            field=models.CharField(
                default="en", max_length=10, verbose_name="Language"
            ),
        ),
        migrations.AddField(
            model_name="prediction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predictions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Farmer",
            ),
        ),
    ]
